### ISSUE TITLE
Drop outside player inventory bug (and solution, and question)

### ISSUE THREAD

**Issue by DanSteph1024** [Krsmanovic-S/Complete-Inventory-Documentation#3]
Hi Stefan,

One small bug, if we drop an item outside a player's slot it fall in the world:
![image](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/137847058/8d4665f7-ee76-42e1-9c9f-15af5ee63a68)

Solution is as follow:
![image](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/137847058/3a60c302-2136-4c5e-a733-008dba166771)

**Question:** :)

I would like that a "back pack" extend the 8 existing slots to 24, like in the game "Raft".
I would be also nice that it happen dynamically, without closing the inventory.
Everything is hard-constructed in "BeginPlay", so it's hard to change the number of slots without a massive change.

Maybe it would be better to hide/show the 16 missing slot on demand ? In this case do you have any direction where to search/do this things  ?

![image](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/137847058/8ddd54d1-7bbd-4886-acfa-8bf584f0a353)

Much thanks & best regards

Dan

**Comment by DanSteph1024** [comment]
Hi Stefan,

Never mind the question, I found a way with a new variable "FItemStruct->visible" and some modification in "ConstructAllSlots" and "RefreshAllSlot" of WGB_Inventory. The slots appear/disappear nicely in real time when the backpack is mounted unmounted.
Now it's a question of coding details.
![image](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/137847058/e809dcb0-0278-46a7-bc8f-8c06962aeec3)

I leave this open until you reply and will close this issue.

Best regards

Dan

**Comment by Krsmanovic-S** [comment]
Hello Dan,

> One small bug, if we drop an item outside a player's slot it fall in the world:

I've noticed this and it was quickly patched in the newest release for the plugin, so no worries!

> Never mind the question, I found a way with a new variable "FItemStruct->visible" and some modification in "ConstructAllSlots" and "RefreshAllSlot" of WGB_Inventory. The slots appear/disappear nicely in real time when the backpack is mounted unmounted.
Now it's a question of coding details

Great job on figuring it out, I like the approach! I am looking into adding bags of sorts to the plugin as well as some more stuff but I am currently between some projects so that will wait for now. Interacting between the bag and the main inventory is already there so you shouldn't have any trouble with it :)
